export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SIGN_UP_USER = "SIGN_UP_USER";

export const GET_DOCUMENT_LIST = "GET_DOCUMENT_LIST";
export const ADD_DOCUMENT_LIST = "ADD_DOCUMENT_LIST";
export const UPDATE_DOCUMENT_LIST = "UPDATE_DOCUMENT_LIST";
export const GET_SINGLE_DOCUMENT = "GET_SINGLE_DOCUMENT";
export const DELETE_DOCUMENT_LIST = "DELETE_DOCUMENT_LIST";
export const CLEAR_SINGLE_DOCUMENT = "CLEAR_SINGLE_DOCUMENT";
export const CLEAR_APP_DATA = "CLEAR_APP_DATA";

export const IS_LOADING_TRUE = "IS_LOADING_TRUE";
export const IS_LOADING_FALSE = "IS_LOADING_FALSE";
